### ISSUE TITLE
Fails to compile.

### ISSUE THREAD

**Issue by BLamy** [susam/bfc#2]
http://gyazo.com/180c938cce672313938bac86f9ba8ddc.png

**Comment by susam** [comment]
The program given in the screenshot is accessing a cell beyond the first valid cell. Here is the program replicated in text form:

```brainfuck
++++++++++[>+++++++>++++++++++>+<<<<-]>++.>+.+++++++..+++.>++.<<++++++++++++++
+.>.+++.------.--------.>+.>.
```

The program becomes invalid when the first `-` is encountered:

```brainfuck
++++++++++[>+++++++>++++++++++>+<<<<-
```

This sets cell 0 to 10, cell 1 to 7, cell 2 to 10, and cell 3 to 1. Then it decrements the cell pointer by 4 to point to cell -1. This is an invalid cell that is one cell beyond the first valid cell (cell 0).

A simple fix would be to change `<<<<` to `<<<` instead so that the pointer moves back to cell 0 as desired and decrements the counter value there as the loop iterates. The complete program would look like this then:

```brainfuck
++++++++++[>+++++++>++++++++++>+<<<-]>++.>+.+++++++..+++.>++.<<++++++++++++++
+.>.+++.------.--------.>+.>.
```

Here is the output:

```brainfuck
$ ./bfc hello.bf && ./hello
Hello
```
